using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectHubAPI.Data;
using ProjectHubAPI.Models;

namespace ProjectHubAPI.Controllers
{
    [ApiController]
        [Route("api/[controller]")]
            [Authorize] 
                public class UserController : ControllerBase
                    {
                            private readonly AppDbContext _context;

                                    public UserController(AppDbContext context)
                                            {
                                                        _context = context;
                                                                }

                                                                        [HttpGet]
                                                                                public IActionResult GetUsers()
                                                                                        {
                                                                                                    var users = _context.Users
                                                                                                                    .Include(u => u.Role)
                                                                                                                                    .Select(u => new {
                                                                                                                                                        u.Id,
                                                                                                                                                                            u.Name,
                                                                                                                                                                                                u.Email,
                                                                                                                                                                                                                    RoleName = u.Role != null ? u.Role.Name : "User"
                                                                                                                                                                                                                                    }).ToList();
                                                                                                                                                                                                                                                return Ok(users);
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                [HttpPost]
                                                                                                                                                                                                                                                                        [Authorize(Roles = "Admin")]
                                                                                                                                                                                                                                                                                public IActionResult CreateUser(User user)
                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                    _context.Users.Add(user);
                                                                                                                                                                                                                                                                                                                _context.SaveChanges();
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                            return Ok(user);
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                            [HttpPut("{id}")]
                                                                                                                                                                                                                                                                                                                                                    [Authorize(Roles = "Admin")]
                                                                                                                                                                                                                                                                                                                                                            public IActionResult UpdateUser(int id, User user)
                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                var existing = _context.Users.Find(id);
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                            if (existing == null)
                                                                                                                                                                                                                                                                                                                                                                                                            return NotFound();
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                        existing.Name = user.Name;
                                                                                                                                                                                                                                                                                                                                                                                                                                    existing.Email = user.Email;
                                                                                                                                                                                                                                                                                                                                                                                                                                                existing.Password = user.Password;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            existing.RoleId = user.RoleId;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        _context.SaveChanges();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return Ok(existing);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [HttpDelete("{id}")]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            [Authorize(Roles = "Admin")]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public IActionResult DeleteUser(int id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    var user = _context.Users.Find(id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (user == null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return NotFound();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Remove related records first to avoid foreign key constraint violations
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var taskAssignments = _context.TaskAssignments.Where(ta => ta.UserId == id).ToList();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (taskAssignments.Any())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            _context.TaskAssignments.RemoveRange(taskAssignments);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var comments = _context.Comments.Where(c => c.UserId == id).ToList();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (comments.Any())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _context.Comments.RemoveRange(comments);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _context.Users.Remove(user);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _context.SaveChanges();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return Ok(new { message = "User and related records deleted successfully." });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        catch (Exception ex)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return BadRequest(new { message = "Failed to delete user: " + ex.Message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectHubAPI.Data;
using ProjectHubAPI.Models;

namespace ProjectHubAPI.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    [Authorize] 
    public class UserController : ControllerBase
    {
        private readonly AppDbContext _context;

        public UserController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult GetUsers()
        {
            var users = _context.Users
                .Include(u => u.Role)
                .Select(u => new {
                    u.Id,
                    u.Name,
                    u.Email,
                    RoleName = u.Role != null ? u.Role.Name : "User"
                }).ToList();
            return Ok(users);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult CreateUser(User user)
        {
            _context.Users.Add(user);
            _context.SaveChanges();

            return Ok(user);
        }

        [HttpPut("{id}")]
        [Authorize(Roles = "Admin")]
        public IActionResult UpdateUser(int id, User user)
        {
            var existing = _context.Users.Find(id);

            if (existing == null)
                return NotFound();

            existing.Name = user.Name;
            existing.Email = user.Email;
            existing.Password = user.Password;
            existing.RoleId = user.RoleId;

            _context.SaveChanges();

            return Ok(existing);
        }

        [HttpDelete("{id}")]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteUser(int id)
        {
            var user = _context.Users.Find(id);

            if (user == null)
                return NotFound();

            _context.Users.Remove(user);
            _context.SaveChanges();

            return Ok();
        }
    }
}

